const data = {
  products: [
    {
      name: "Nike Sports Shoes 1",
      price: "160",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/MGfFQxL/footwear1.jpg",
    },
    {
      name: "Nike Sports Shoes 2",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/SvmsGLB/footwear2.jpg"
      
    },
    {
      name: "Nike Sports Shoes 3",
      price: "250",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/VgQxStY/footwear3.jpg"
    
    },
    {
      name: "Nike Sports Shoes 4",
      price: "320",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/bJzHzQw/footwear4.jpg"
    },
    {
      name: "Nike Sports Shoes 5",
      price: "700",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/MGfFQxL/footwear1.jpg",
    },
    {
      name: "Nike Sports Shoes 6",
      price: "465",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/SvmsGLB/footwear2.jpg",
    },
    {
      name: "Nike Sports Shoes 7",
      price: "900",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/VgQxStY/footwear3.jpg",
    },
    {
      name: "Nike Sports Shoes 8",
      price: "650",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/bJzHzQw/footwear4.jpg",
    },
    {
      name: "Nike Sports Shoes 9",
      price: "800",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/MGfFQxL/footwear1.jpg",
    },
    {
      name: "Nike Sports Shoes 10",
      price: "730",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/SvmsGLB/footwear2.jpg",
    },
    {
      name: "Nike Sports Shoes 11",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/VgQxStY/footwear3.jpg",
    },
    {
      name: "Nike Sports Shoes 12",
      price: "299",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "footwear",
      imgurl:"https://i.ibb.co/bJzHzQw/footwear4.jpg",
    },

    {
      name: "Bed",
      price: "690",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
      imgurl:"https://i.ibb.co/sF3DDb1/bed.jpg",  
},
    {
      name: "Bedsheet",
      price: "490",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/rHZd1mg/bedsheet.jpg",  
},
    {
      name: "Towel",
      price: "370",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/4SLgr2p/blanket.jpg",  
},
    {
      name: "Door Mat",
      price: "270",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/5RyJHSB/carpet.jpg",  
},
    {
      name: "Bed",
      price: "170",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/sF3DDb1/bed.jpg",  
},
    {
      name: "Bedsheet",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/rHZd1mg/bedsheet.jpg",  
},
    {
      name: "Towel",
      price: "999",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/4SLgr2p/blanket.jpg",  
},
    {
      name: "Door Mat",
      price: "565",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/5RyJHSB/carpet.jpg",  
},
    {
      name: "Bed",
      price: "642",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/sF3DDb1/bed.jpg",  
},
    {
      name: "Bedsheet",
      price: "750",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/rHZd1mg/bedsheet.jpg",  
},
    {
      name: "Towel",
      price: "370",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/4SLgr2p/blanket.jpg",  
},
    {
      name: "Door Mat",
      price: "220",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "home",
  
  imgurl:"https://i.ibb.co/5RyJHSB/carpet.jpg",  
},

    {
      name: "Purse",
      price: "599",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/yBcFF1t/fashion.png",
    },
    {
      name: "Sunglasses",
      price: "279",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/YdvNYWL/sunglasses.jpg",
    },
    {
      name: "Wallet",
      price: "330",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/DQ8yn1G/wallet.jpg",
    },
    {
      name: "Watch",
      price: "1000",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/ydbZz0C/watch.jpg",
    },
    {
      name: "Purse",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/yBcFF1t/fashion.png",
    },
    {
      name: "Sunglasses",
      price: "100",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/YdvNYWL/sunglasses.jpg",
    },
    {
      name: "Wallet",
      price: "450",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/DQ8yn1G/wallet.jpg",
    },
    {
      name: "Watch",
      price: "775",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/ydbZz0C/watch.jpg",
    },
    {
      name: "Purse",
      price: "175",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/yBcFF1t/fashion.png",
    },
    {
      name: "Sunglasses",
      price: "280",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/YdvNYWL/sunglasses.jpg",
    },
    {
      name: "Wallet",
      price: "460",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/DQ8yn1G/wallet.jpg",
    },
    {
      name: "Watch",
      price: "670",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "fashion",
      imgurl:"https://i.ibb.co/ydbZz0C/watch.jpg",
    },

    {
      name: "IPhone 12",
      price: "299",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/MCCpp9z/iphone.jpg",
    },
    {
      name: "Oppo A74 5G",
      price: "199",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/VWPrHs5/mobile.jpg",
    },
    {
      name: "Google Pixel 5",
      price: "999",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/GRYsWJv/pixel5.jpg",
    },
    {
      name: "Samsung S20",
      price: "459",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/7XRMMbW/samsung.jpg",
    },
    {
      name: "IPhone 12",
      price: "569",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/MCCpp9z/iphone.jpg",
    },
    {
      name: "Oppo A74 5G",
      price: "189",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/VWPrHs5/mobile.jpg",
    },
    {
      name: "Google Pixel 5",
      price: "989",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/GRYsWJv/pixel5.jpg",
    },
    {
      name: "Samsung S20",
      price: "1000",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/7XRMMbW/samsung.jpg",
    },
    {
      name: "Iphone 12",
      price: "480",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/MCCpp9z/iphone.jpg",
    },
    {
      name: "Oppo A74 5G",
      price: "260",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/VWPrHs5/mobile.jpg",
    },
    {
      name: "Google Pixel 5",
      price: "780",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/GRYsWJv/pixel5.jpg",
    },
    {
      name: "Samsung S20",
      price: "333",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "mobiles",
      imgurl:"https://i.ibb.co/7XRMMbW/samsung.jpg",
    },

    {
      name: "Bed",
      price: "179",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/sF3DDb1/bed.jpg",
    },
    {
      name: "Mattress",
      price: "289",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/wRxjPcH/mattress.jpg",
    },
    {
      name: "Office Chair",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/ChK3VrQ/officechair.jpg",
    },
    {
      name: "Sofa",
      price: "999",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/2h3XY55/sofa.jpg",
    },
    {
      name: "Bed",
      price: "899",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/sF3DDb1/bed.jpg",
    },
    {
      name: "Mattress",
      price: "650",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/wRxjPcH/mattress.jpg",
    },
    {
      name: "Office Chair",
      price: "560",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/ChK3VrQ/officechair.jpg",
    },
    {
      name: "Sofa",
      price: "730",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/2h3XY55/sofa.jpg",
    },
    {
      name: "Bed",
      price: "930",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/sF3DDb1/bed.jpg",
    },
    {
      name: "Mattress",
      price: "235",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/wRxjPcH/mattress.jpg",
    },
    {
      name: "Office Chair",
      price: "355",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/ChK3VrQ/officechair.jpg",
    },
    {
      name: "Sofa",
      price: "865",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "furniture",
      imgurl:"https://i.ibb.co/2h3XY55/sofa.jpg",
    },
  ],
};

export default data;


{/* <a href="https://imgbb.com/"><img src="https://i.ibb.co/t4Wpw1T/bedsheet.jpg" alt="bedsheet" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/g73QLsV/fashion.png" alt="fashion" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/MGfFQxL/footwear1.jpg" alt="footwear1" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/SvmsGLB/footwear2.jpg" alt="footwear2" border="0"></a>
<a href="https://ibb.co/v3QhPH4"><img src="https://i.ibb.co/VgQxStY/footwear3.jpg" alt="footwear3" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/bJzHzQw/footwear4.jpg" alt="footwear4" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/Rh2QF7s/grocery.jpg" alt="grocery" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/b285frP/mobile.jpg" alt="mobile" border="0"></a> */}