const data = {
  products: [
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Footwear",
    },

    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Home",
    },

    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Travel",
    },

    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Mobiles",
    },

    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
    {
      name: "Nike1",
      price: "399",
      originalprice: "2000",
      desc: "Good Shoes",
      category: "Grocery",
    },
  ],
};

export default data;
